InnerLoop:
  AttitudeController:
    MC_ROLL_P: 11.5
    MC_PITCH_P: 6.5
    MC_YAW_P: 2.8
    MC_YAW_WEIGHT: 0.4
    MAX_CONTROL_ANGLE_RATE_PITCH: 220
    MAX_CONTROL_ANGLE_RATE_ROLL: 220
    MAX_CONTROL_ANGLE_RATE_YAW: 200

  AngularRateController:
    MC_ROLLRATE_P: 0.055
    MC_ROLLRATE_I: 0.2
    MC_ROLLRATE_D: 0.0005
    MC_PITCHRATE_P: 0.06
    MC_PITCHRATE_I: 0.2
    MC_PITCHRATE_D: 0.0005
    MC_YAWRATE_P: 0.2
    MC_YAWRATE_I: 0.1
    MC_YAWRATE_D: 0.00
    dt: 0.01

MotorModel:
  scale_factor: 3480.7
  offset_factor: 445.7799
  time_constant: 0.02
  initial_conditions: 0.0
  dt: 0.01
